### ISSUE TITLE
tm-master often crashes when it's about to finish the jobs

### ISSUE THREAD

**Issue by flc** [dcramer/taskmaster#2]
i often run into a problem that tm-master crashes when it's about to finish the jobs.
here is the traceback from tm-master:
http://dpaste.com/hold/745136/

here is the traceback from tm-spawn:
http://dpaste.com/hold/745139/

any idea why is that?

(btw thx for making things like taskmaster open source, keep up the great work)

**Comment by dcramer** [comment]
Hrm I haven't seen the issue (on master), but I thought we were handling EOFErrors.

Does this happen towards the end of the queue, or just on all jobs?

**Comment by flc** [comment]
definitely only towards the end of the queue ...

**Comment by flc** [comment]
it seems it works fine with the latest version (0.5.2), thx
